### ISSUE TITLE
ポータブル版セットアップ手順のUbuntuで使用するためのパッケージが16.04以降では足りない

### ISSUE THREAD

**Issue by nogajun** [outerguy/moneysound#1]
[ポータブル版セットアップ手順](https://www.beatrek.com/home/moneysound/portable/install.htm#ud)にUbuntuで使用する前のセットアップで

> 端末で「sudo apt-get install php5-cli」を入力します。

と記載がありますが、Ubuntu 16.04以降はPHP7が標準でパッケージングが変わったので利用をするにはphp-cliのほかにphp-xmlとphp-mbstringパッケージが必要になります。

> sudo apt install php-cli php-xml php-mbstring

これで使えると思います。

**Comment by outerguy** [comment]
ご指摘くださりありがとうございます。修正いたしました。
あいにくUbuntuの検証環境が整わないため、机上での修正確認に留めております。
適切でない修正箇所がございましたら、改めてご指摘いただけますと幸いです。

**Comment by nogajun** [comment]
確認しました。ありがとうございます。
